останавливает код после throw как return
 throw new Error('...')